name: duration_picker
description: A widget for picking durations, inspired by Material Time Picker.
version: 1.0.4
homepage: https://github.com/cdharris/flutter_duration_picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
   sdk: ">=2.12.0 <3.0.0"
