name: flutter_duration_picker
description: A widget for picking durations, inspired by Material Time Picker.
version: 2.0.1
author: Mehmet Gürol Çay (Chris Harris <c@harrischris.com>)
homepage: https://github.com/gurolcay/flutter_duration_picker
original project: https://github.com/cdharris/flutter_duration_picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4 <2.0.0"
